-- Create HC Candidate Offerings table
CREATE TABLE IF NOT EXISTS hero_hc_candidate_offerings (
  id SERIAL PRIMARY KEY,
  candidate_id INTEGER NOT NULL UNIQUE REFERENCES hero_hc_candidates(id) ON DELETE CASCADE,
  position TEXT NOT NULL DEFAULT '',
  direct_supervisor TEXT NOT NULL DEFAULT '',
  salary TEXT NOT NULL DEFAULT '',
  contract_duration_months INTEGER NOT NULL DEFAULT 12,
  start_date DATE,
  outpatient_benefit TEXT NOT NULL DEFAULT 'Penusahaan memberikan bantuan biaya pengobatan rawat jalan sebesar Rp 3.500.000,-',
  inpatient_benefit TEXT NOT NULL DEFAULT 'Penusahaan akan memberikan biaya penggatan/Pengobatan sepengetahuan bagi karyawan beserta istri & 3 (tiga) anak yang sah secara hukum, apabila telah ditanggung menjadi tanggungan karyawan tetap',
  maternity_benefit TEXT NOT NULL DEFAULT 'Penusahaan akan memberikan bantuan sebesar Rp 8.000.000,-. Dan apabila dilakukan operasi caesar perusahaan akan mengganti biaya peralatan sebesar Rp 15.000.000, setelah ditanggung menjadi tanggungan karyawan tetap',
  accident_insurance TEXT NOT NULL DEFAULT 'Penusahaan akan menanggung premi asuransi sepengetahuannya',
  bpjs_employment TEXT NOT NULL DEFAULT 'Wajib berdasarkan Peraturan Pemerintah',
  bpjs_health TEXT NOT NULL DEFAULT 'Wajib berdasarkan Peraturan Pemerintah',
  thr TEXT NOT NULL DEFAULT 'Penusahaan akan memberikan THR setahun upah, dan apabila Saudara belum mencapai masa kerja 1 (satu) tahun tetapi sudah lebih dari 1 (satu) bulan, maka akan dihitung secara proporsional.',
  other_terms TEXT NOT NULL DEFAULT 'Ketentuan-ketentuan lain yang tidak secara khusus diatur dalam penawaran diatas (Biaya Perjalanan Dinas, Bantuan dan fasilitas lain dan perusahaan) akan tunduk pada peraturan/perjanjian karyawan yang berlaku. Pokok-pokok Musyawarah serta tetapkan pelaksanaan perusahaan',
  signatory_name TEXT NOT NULL DEFAULT '',
  signatory_title TEXT NOT NULL DEFAULT '',
  signature_url TEXT NOT NULL DEFAULT '',
  letter_number TEXT NOT NULL DEFAULT '',
  pdf_url TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'Draft',
  sent_at TIMESTAMP,
  responded_at TIMESTAMP,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
