CREATE TABLE IF NOT EXISTS "hero_recruitment_section_templates" (
	"id" serial PRIMARY KEY NOT NULL,
	"section_id" integer,
	"requirements" text DEFAULT '' NOT NULL,
	"qualifications" jsonb DEFAULT '[]',
	"mandatory_fields" jsonb DEFAULT '[]',
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'hero_recruitment_section_templates_section_id_hero_master_sections_id_fk'
  ) THEN
    ALTER TABLE "hero_recruitment_section_templates" ADD CONSTRAINT "hero_recruitment_section_templates_section_id_hero_master_sections_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."hero_master_sections"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "hero_recruitment_section_templates_section_id_idx" ON "hero_recruitment_section_templates" ("section_id");

-- Templates are auto-generated by seed script per active section
-- No manual inserts needed; seed script covers all sections
