import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const read = (file) => readFileSync(path.join(process.cwd(), file), 'utf8')

test('mobile tire damage keeps Vision credentials server-side and enforces existing inspection access', () => {
  const route = read('app/api/mobile/tire-damage/predict/route.ts')
  const feedbackRoute = read('app/api/mobile/tire-damage/feedback/route.ts')
  const downloadRoute = read('app/api/mobile/tire-damage/download/route.ts')
  const client = read('app/mobile/hse/tire-damage/page.tsx')
  const visionClient = read('lib/raray-vision/client.ts')
  const chatRoute = read('app/api/chat/route.ts')
  const geniusAction = read('app/dashboard/hero-genius/actions.ts')
  const mobileGeniusChat = read('components/mobile/mobile-genius-chat.tsx')

  assert.match(route, /getCurrentMenuPermission\('hse_tire_inspection'\)/)
  assert.match(route, /ALLOWED_MEDIA_TYPES/)
  assert.match(client, /fetch\('\/api\/mobile\/tire-damage\/predict'/)
  assert.match(client, /MAX_IMAGE_DIMENSION = 1600/)
  assert.match(client, /image\/jpeg', 0\.82/)
  assert.match(client, /createImageBitmap/)
  assert.match(client, /Menyiapkan foto agar unggah lebih cepat/)
  assert.doesNotMatch(client, /HSE • AI INSPECTION/)
  assert.match(client, /transition-\[width\] duration-700/)
  assert.match(client, /animate-pulse/)
  assert.match(client, /findDamageDetails/)
  assert.match(client, /Luka terdeteksi/)
  assert.match(client, /\{damage\.label\}/)
  assert.match(client, /elapsedSeconds/)
  assert.match(client, /getUserMedia/)
  assert.match(client, /facingMode: \{ ideal: 'environment' \}/)
  assert.match(client, /Ambil Foto/)
  assert.doesNotMatch(client, /capture="environment"/)
  assert.match(client, /buildGeniusPrompt/)
  assert.match(client, /Tanya HERO Genius/)
  assert.match(client, /mode=tire-specialist/)
  assert.match(mobileGeniusChat, /mode === "tire-specialist"/)
  assert.match(chatRoute, /body\.mode === "tire-specialist"/)
  assert.match(chatRoute, /role === "user" \|\|/)
  assert.doesNotMatch(chatRoute, /role === "system"/)
  assert.match(geniusAction, /spesialis Tire Inspection dan Tire Repair/)
  assert.match(
    geniusAction,
    /Jika dokumen tidak membahas kasusnya, tetap jawab berdasarkan pengetahuan teknis AI/
  )
  assert.match(client, /Unduh Gambar/)
  assert.doesNotMatch(client, /JSON\.stringify\(result, null, 2\)/)
  assert.match(downloadRoute, /Content-Disposition/)
  assert.match(downloadRoute, /is3\.cloudhost\.id/)
  assert.doesNotMatch(client, /RARAY_VISION_API_KEY|rv_c861/)
  assert.match(visionClient, /tire-demage-onnx/)
  assert.match(visionClient, /tire-demage/)
  assert.match(visionClient, /3_000/)
  assert.match(visionClient, /let primary: Response \| undefined/)
  assert.match(feedbackRoute, /getCurrentMenuPermission\('hse_tire_inspection'\)/)
  assert.match(feedbackRoute, /canEdit/)
  assert.match(feedbackRoute, /prediction_id/)
  assert.match(feedbackRoute, /shape.*rectangle/)
  assert.match(feedbackRoute, /TIRE_DAMAGE_LABELS/)
  assert.match(feedbackRoute, /sidewall separation/)
  assert.match(feedbackRoute, /annotation\.x \* imageWidth/)
  assert.match(visionClient, /raraySubmitTireDamageFeedback/)
  assert.match(client, /Apakah hasil ini akurat\?/)
  assert.match(client, /Kirim koreksi/)
  assert.match(client, /onPointerDown={startFeedbackBox}/)
  assert.match(client, /Tarik kotak pada area kerusakan/)
  assert.doesNotMatch(client, /RARAY_VISION_API_KEY|RARAY_VISION_PASSWORD/)
})
