import { Badge } from "@/components/ui/badge";

const toneMap: Record<string, string> = {
  approved: "bg-emerald-100 text-emerald-900",
  approved_today: "bg-emerald-100 text-emerald-900",
  approved_today_display: "bg-emerald-100 text-emerald-900",
  pending: "bg-amber-100 text-amber-900",
  pending_l2: "bg-amber-100 text-amber-900",
  pending_l1: "bg-amber-100 text-amber-900",
  in_review: "bg-amber-100 text-amber-900",
  draft_ready: "bg-sky-100 text-sky-900",
  draft: "bg-sky-100 text-sky-900",
  cancelled: "bg-slate-200 text-slate-900",
  ready_for_payroll: "bg-emerald-100 text-emerald-900",
  needs_correction: "bg-rose-100 text-rose-900",
  needs_revision: "bg-rose-100 text-rose-900",
  revised: "bg-rose-100 text-rose-900",
  rejected: "bg-slate-200 text-slate-900",
  skipped: "bg-slate-100 text-slate-800",
  delegated: "bg-sky-100 text-sky-900",
  expiring_soon: "bg-amber-100 text-amber-900",
  urgent: "bg-rose-100 text-rose-900",
  active: "bg-emerald-100 text-emerald-900",
  expired: "bg-rose-100 text-rose-900",
  inactive: "bg-slate-200 text-slate-900",
  probation: "bg-sky-100 text-sky-900",
  contract: "bg-violet-100 text-violet-900",
  on_leave: "bg-amber-100 text-amber-900",
  resigned: "bg-slate-200 text-slate-900",
  healthy: "bg-emerald-100 text-emerald-900",
  follow_up: "bg-amber-100 text-amber-900",
  attention: "bg-rose-100 text-rose-900",
  open: "bg-rose-100 text-rose-900",
  action_taken: "bg-emerald-100 text-emerald-900",
  investigating: "bg-amber-100 text-amber-900",
  closed: "bg-emerald-100 text-emerald-900",
  verified: "bg-emerald-100 text-emerald-900",
  needs_review: "bg-amber-100 text-amber-900",
  overtime: "bg-sky-100 text-sky-900",
  emergency: "bg-rose-100 text-rose-900",
  safety: "bg-amber-100 text-amber-900",
  submitted: "bg-amber-100 text-amber-900",
  waiting: "bg-slate-100 text-slate-800",
  comment: "bg-slate-100 text-slate-800",
  overdue: "bg-rose-100 text-rose-900",
  due_soon: "bg-amber-100 text-amber-900",
  on_track: "bg-sky-100 text-sky-900",
  live: "bg-emerald-100 text-emerald-900",
  ready: "bg-emerald-100 text-emerald-900",
  partial: "bg-sky-100 text-sky-900",
  backlog: "bg-slate-200 text-slate-900",
  planned: "bg-slate-200 text-slate-900",
  blueprint: "bg-sky-100 text-sky-900",
  queued: "bg-sky-100 text-sky-900",
  sent: "bg-emerald-100 text-emerald-900",
  failed: "bg-rose-100 text-rose-900",
  scheduled: "bg-sky-100 text-sky-900",
  executed: "bg-emerald-100 text-emerald-900",
  approval: "bg-amber-100 text-amber-900",
  delegation: "bg-sky-100 text-sky-900",
  escalation: "bg-rose-100 text-rose-900",
  email: "bg-sky-100 text-sky-900",
  in_app: "bg-emerald-100 text-emerald-900",
  before_due: "bg-amber-100 text-amber-900",
};

function normalize(value: string) {
  return value.toLowerCase().replaceAll(" ", "_");
}

const labelMap: Record<string, string> = {
  approved: "Disetujui",
  approved_today: "Disetujui hari ini",
  approved_today_display: "Disetujui hari ini",
  pending: "Menunggu",
  pending_l2: "Menunggu pemeriksa 2",
  pending_l1: "Menunggu pemeriksa 1",
  in_review: "Ditinjau",
  draft_ready: "Draft siap",
  draft: "Draft",
  cancelled: "Dibatalkan",
  ready_for_payroll: "Siap payroll",
  needs_correction: "Perlu koreksi",
  needs_revision: "Perlu revisi",
  revised: "Direvisi",
  rejected: "Ditolak",
  skipped: "Dilewati",
  delegated: "Didelegasikan",
  expiring_soon: "Hampir berakhir",
  urgent: "Mendesak",
  active: "Aktif",
  expired: "Expired",
  inactive: "Nonaktif",
  probation: "Probation",
  contract: "Kontrak",
  on_leave: "Cuti",
  resigned: "Resign",
  healthy: "Aman",
  follow_up: "Perlu tindak lanjut",
  attention: "Perlu perhatian",
  open: "Terbuka",
  action_taken: "Ditangani",
  investigating: "Ditinjau",
  closed: "Selesai",
  verified: "Terverifikasi",
  needs_review: "Perlu review",
  overtime: "Lembur",
  emergency: "Darurat",
  safety: "Keselamatan",
  submitted: "Dikirim",
  waiting: "Menunggu",
  comment: "Komentar",
  overdue: "Terlambat",
  due_soon: "Segera jatuh tempo",
  on_track: "Sesuai rencana",
  live: "Aktif",
  ready: "Siap",
  partial: "Sebagian siap",
  backlog: "Direncanakan",
  planned: "Direncanakan",
  blueprint: "Rancangan",
  queued: "Menunggu",
  sent: "Terkirim",
  failed: "Gagal",
  scheduled: "Terjadwal",
  executed: "Selesai",
  approval: "Approval",
  delegation: "Delegasi",
  escalation: "Eskalasi",
  email: "Email",
  in_app: "Di aplikasi",
  before_due: "Sebelum jatuh tempo",
};

export function AdminStatusBadge({ value }: { value: string }) {
  const key = normalize(value);
  const className = toneMap[key] ?? "bg-slate-100 text-slate-800";

  return (
    <Badge className={`rounded-full border-0 px-3 py-1 font-medium ${className}`}>
      {labelMap[key] ?? value.replaceAll("_", " ")}
    </Badge>
  );
}
