export const approvalSummary = {
  waitingLevel1: 6,
  waitingLevel2: 3,
  escalated: 2,
  approvedToday: 14,
};

export const approvalQueue = [
  {
    id: "APR-901",
    employee: "Arman Saputra",
    role: "Technician",
    site: "Bengalon Pit North",
    level: "Level 1",
    type: "Tire Service",
    unit: "HD785-17",
    submittedAt: "13:55",
    workedHours: "5.5 jam",
    overtime: "1.5 jam",
    status: "Need Review",
    risk: "Emergency",
    notes:
      "Ban OTR sisi kanan belakang berhasil dipasang. Perlu verifikasi foto final dan alasan overtime.",
    photos: 4,
    checklist: [
      "Foto sebelum dan sesudah tersedia",
      "GPS check-in valid",
      "Status emergency dipilih",
      "Overtime melebihi 1 jam",
    ],
  },
  {
    id: "APR-902",
    employee: "Soni Darmawan",
    role: "HSE Officer",
    site: "Bengalon Pit North",
    level: "Level 1",
    type: "HSE Patrol",
    unit: "Area Pit North",
    submittedAt: "14:10",
    workedHours: "3 jam",
    overtime: "0 jam",
    status: "Need Review",
    risk: "Safety",
    notes:
      "Patrol area pit north dengan temuan blind spot haul road dan APD tidak lengkap pada vendor.",
    photos: 3,
    checklist: [
      "Checklist patrol lengkap",
      "3 foto observasi terunggah",
      "Tindakan korektif dicatat",
    ],
  },
  {
    id: "APR-903",
    employee: "Mira Andini",
    role: "Admin Site",
    site: "Bengalon Pit North",
    level: "Level 2",
    type: "Daily Recap",
    unit: "Site manpower",
    submittedAt: "14:03",
    workedHours: "2 jam",
    overtime: "0 jam",
    status: "Need Review",
    risk: "Normal",
    notes:
      "Rekap manpower dan absensi shift pagi. Perlu final approval PJO setelah dicek foreman.",
    photos: 0,
    checklist: [
      "Headcount sesuai absensi",
      "Izin dan sakit sudah ditandai",
      "Siap masuk daily report",
    ],
  },
  {
    id: "APR-894",
    employee: "Fikri Maulana",
    role: "Technician",
    site: "Bengalon Pit North",
    level: "Level 1",
    type: "Tire Inspection",
    unit: "DT-23 sampai DT-28",
    submittedAt: "11:42",
    workedHours: "2.5 jam",
    overtime: "0 jam",
    status: "Approved Today",
    risk: "Normal",
    notes:
      "Inspeksi rutin 6 unit, ditemukan 1 tekanan ban di bawah standar dan sudah diberi catatan.",
    photos: 2,
    checklist: [
      "Form inspeksi lengkap",
      "Tekanan abnormal ditandai",
      "Foto kondisi ban terlampir",
    ],
  },
  {
    id: "APR-887",
    employee: "Dedi Pranata",
    role: "Foreman",
    site: "Satui Support Site",
    level: "Level 2",
    type: "Overtime Recap",
    unit: "Night shift team A",
    submittedAt: "09:08",
    workedHours: "11 jam",
    overtime: "3 jam",
    status: "Escalated",
    risk: "Emergency",
    notes:
      "Lembur tim malam karena breakdown unit customer. Butuh review cepat HC karena melewati threshold site.",
    photos: 1,
    checklist: [
      "Surat tugas lembur dilampirkan",
      "Threshold overtime terlampaui",
      "Perlu approval lintas level",
    ],
  },
] as const;
