export type EmailTemplatePreset = {
  name: string
  templateCode: string
  templateType: string
  deliveryChannel: string
  recipientScope: string
  ccEmail: string
  subject: string
  htmlContent: string
  textContent: string
  description: string
  variables: string[]
  sampleValues: Record<string, string>
}

export const EMAIL_TEMPLATE_PRESETS: EmailTemplatePreset[] = [
  {
    name: 'Approval Assignment',
    templateCode: 'approval_assignment',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'approver',
    ccEmail: '',
    subject: 'Tugas approval baru #{{requestId}}',
    htmlContent: '<p>Request #{{requestId}} menunggu approval Anda.</p>',
    textContent: 'Request #{{requestId}} menunggu approval Anda.',
    description: 'Notifikasi saat request masuk ke approver.',
    variables: ['requestId'],
    sampleValues: {
      requestId: 'APR-2026-0142',
    },
  },
  {
    name: 'Approval SLA Reminder',
    templateCode: 'approval_sla_reminder',
    templateType: 'Reminder',
    deliveryChannel: 'email,bell,pwa_push',
    recipientScope: 'approver',
    ccEmail: '',
    subject: 'Reminder SLA untuk request #{{requestId}}',
    htmlContent: '<p>SLA request #{{requestId}} hampir jatuh tempo.</p>',
    textContent: 'SLA request #{{requestId}} hampir jatuh tempo.',
    description: 'Reminder otomatis untuk approval yang mendekati SLA.',
    variables: ['requestId'],
    sampleValues: {
      requestId: 'APR-2026-0142',
    },
  },
  {
    name: 'Attendance Permission Reminder',
    templateCode: 'attendance_permission_reminder',
    templateType: 'Reminder',
    deliveryChannel: 'email,bell',
    recipientScope: 'hc,approver',
    ccEmail: '',
    subject: 'Reminder approval izin {{employeeName}}',
    htmlContent:
      '<p>Izin {{permissionType}} atas nama {{employeeName}} tanggal {{requestDate}} menunggu approval HR.</p>',
    textContent:
      'Izin {{permissionType}} atas nama {{employeeName}} tanggal {{requestDate}} menunggu approval HR.',
    description: 'Reminder pengajuan izin attendance ke HR dan approver terkait.',
    variables: ['employeeName', 'permissionType', 'requestDate'],
    sampleValues: {
      employeeName: 'Budi Santoso',
      permissionType: 'Izin Terlambat',
      requestDate: '18 Juni 2026',
    },
  },
  {
    name: 'Attendance Permission Decision',
    templateCode: 'attendance_permission_decision',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'employee',
    ccEmail: '',
    subject: 'Pengajuan {{permissionType}} Anda {{decisionLabel}}',
    htmlContent:
      '<p>Halo {{employeeName}},</p><p>Pengajuan {{permissionType}} Anda telah {{decisionLabel}}.</p><p>Tanggal: {{requestDate}}</p><p>{{approverNote}}</p>',
    textContent:
      'Halo {{employeeName}}, pengajuan {{permissionType}} Anda telah {{decisionLabel}}. Tanggal: {{requestDate}}. {{approverNote}}',
    description: 'Hasil approve atau reject untuk izin attendance.',
    variables: ['employeeName', 'permissionType', 'decisionLabel', 'requestDate', 'approverNote'],
    sampleValues: {
      employeeName: 'Budi Santoso',
      permissionType: 'Izin Sakit',
      decisionLabel: 'disetujui',
      requestDate: '18 Juni 2026',
      approverNote: 'Catatan approver: lampiran sudah lengkap.',
    },
  },
  {
    name: 'Daily Report Delivery',
    templateCode: 'daily_report_delivery',
    templateType: 'Report',
    deliveryChannel: 'email',
    recipientScope: 'admin,pjo',
    ccEmail: '',
    subject: 'Daily Report {{siteName}} - {{reportDate}}',
    htmlContent: '<p>Daily report {{siteName}} tanggal {{reportDate}} siap dikirim.</p>',
    textContent: 'Daily report {{siteName}} tanggal {{reportDate}} siap dikirim.',
    description: 'Notifikasi report harian untuk pihak operasional.',
    variables: ['siteName', 'reportDate'],
    sampleValues: {
      siteName: 'Site ABN',
      reportDate: '2026-06-18',
    },
  },
  {
    name: 'User Invitation',
    templateCode: 'user_invitation',
    templateType: 'Invitation',
    deliveryChannel: 'email',
    recipientScope: 'employee',
    ccEmail: '',
    subject: 'Undangan akun HERO untuk {{userName}}',
    htmlContent:
      '<p>Halo {{userName}},</p><p>Akun HERO Anda sudah dibuat.</p><p>Terima undangan: <a href="{{invitationLink}}">{{invitationLink}}</a></p><p>Verifikasi email: <a href="{{verificationLink}}">{{verificationLink}}</a></p>',
    textContent:
      'Halo {{userName}}, akun HERO Anda sudah dibuat. Terima undangan: {{invitationLink}}. Verifikasi email: {{verificationLink}}',
    description: 'Email aktivasi akun baru untuk user management.',
    variables: ['userName', 'invitationLink', 'verificationLink'],
    sampleValues: {
      userName: 'Siti Rahma',
      invitationLink: 'https://hero.example.com/auth/accept-invitation?token=sample-invite',
      verificationLink: 'https://hero.example.com/auth/verify-email?token=sample-verify',
    },
  },
  {
    name: 'Onboarding Link',
    templateCode: 'onboarding_link',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'candidate',
    ccEmail: '',
    subject: 'Link onboarding HERO untuk {{candidateName}}',
    htmlContent:
      '<p>Halo {{candidateName}},</p><p>Silakan lengkapi onboarding Anda melalui link berikut:</p><p><a href="{{onboardingLink}}">{{onboardingLink}}</a></p>',
    textContent:
      'Halo {{candidateName}}, silakan lengkapi onboarding Anda melalui link berikut: {{onboardingLink}}',
    description: 'Link onboarding kandidat setelah token dibuat.',
    variables: ['candidateName', 'onboardingLink'],
    sampleValues: {
      candidateName: 'Rina Amelia',
      onboardingLink: 'https://hero.example.com/onboarding/sample-token',
    },
  },
  {
    name: 'Leave Request Submitted',
    templateCode: 'leave_request_submitted',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hc',
    ccEmail: '',
    subject: 'Pengajuan cuti {{leaveTypeName}} dari {{employeeName}}',
    htmlContent:
      '<p>{{employeeName}} mengirim pengajuan cuti {{leaveTypeName}} untuk {{startDate}} sampai {{endDate}} ({{totalDays}} hari).</p><p>{{reason}}</p>',
    textContent:
      '{{employeeName}} mengirim pengajuan cuti {{leaveTypeName}} untuk {{startDate}} sampai {{endDate}} ({{totalDays}} hari). {{reason}}',
    description: 'Notifikasi submit cuti baru ke HC.',
    variables: ['employeeName', 'leaveTypeName', 'startDate', 'endDate', 'totalDays', 'reason'],
    sampleValues: {
      employeeName: 'Andi Saputra',
      leaveTypeName: 'Tahunan',
      startDate: '2026-06-21',
      endDate: '2026-06-23',
      totalDays: '3',
      reason: 'Alasan: keperluan keluarga.',
    },
  },
  {
    name: 'Leave Request Decision',
    templateCode: 'leave_request_decision',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'employee',
    ccEmail: '',
    subject: 'Pengajuan cuti Anda {{decisionLabel}}',
    htmlContent:
      '<p>Halo {{employeeName}},</p><p>Pengajuan cuti {{leaveTypeName}} Anda telah {{decisionLabel}}.</p><p>{{startDate}} sampai {{endDate}}</p><p>{{approverName}}</p><p>{{rejectionReason}}</p>',
    textContent:
      'Halo {{employeeName}}, pengajuan cuti {{leaveTypeName}} Anda telah {{decisionLabel}}. {{startDate}} sampai {{endDate}}. {{approverName}} {{rejectionReason}}',
    description: 'Hasil approval pengajuan cuti ke karyawan.',
    variables: [
      'employeeName',
      'leaveTypeName',
      'decisionLabel',
      'startDate',
      'endDate',
      'approverName',
      'rejectionReason',
    ],
    sampleValues: {
      employeeName: 'Andi Saputra',
      leaveTypeName: 'Tahunan',
      decisionLabel: 'disetujui',
      startDate: '2026-06-21',
      endDate: '2026-06-23',
      approverName: 'Diproses oleh: HC Manager',
      rejectionReason: '',
    },
  },
  {
    name: 'Overtime Assignment',
    templateCode: 'overtime_assignment',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'employee',
    ccEmail: '',
    subject: '{{splNumber}} siap dikerjakan',
    htmlContent:
      '<p>{{title}} dijadwalkan untuk {{workDate}}.</p><p>Nomor SPL: {{splNumber}}</p><p>Jam mulai: {{plannedStart}}</p><p>Jam selesai: {{plannedEnd}}</p>',
    textContent:
      '{{title}} dijadwalkan untuk {{workDate}}. Nomor SPL: {{splNumber}}. Jam mulai: {{plannedStart}}. Jam selesai: {{plannedEnd}}.',
    description: 'Email penugasan SPL/overtime ke karyawan penerima.',
    variables: ['splNumber', 'title', 'workDate', 'plannedStart', 'plannedEnd'],
    sampleValues: {
      splNumber: 'SPL-0626-008',
      title: 'Overtime Shutdown Conveyor',
      workDate: '18 Juni 2026',
      plannedStart: '19:00',
      plannedEnd: '22:00',
    },
  },
  {
    name: 'Daily Activity Pending Approval',
    templateCode: 'daily_activity_pending_approval',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'approver',
    ccEmail: '',
    subject: 'Daily Activity menunggu approval',
    htmlContent:
      '<p>{{employeeName}} mengirim daily activity baru.</p><p>Aktivitas: {{activityTitle}}</p><p>Kategori: {{activityType}}</p><p>Waktu: {{submissionTime}}</p><p>{{notes}}</p>',
    textContent:
      '{{employeeName}} mengirim daily activity baru. Aktivitas: {{activityTitle}}. Kategori: {{activityType}}. Waktu: {{submissionTime}}. {{notes}}',
    description: 'Notifikasi approver saat daily activity perlu review.',
    variables: ['employeeName', 'activityTitle', 'activityType', 'submissionTime', 'notes'],
    sampleValues: {
      employeeName: 'Rudi Hidayat',
      activityTitle: 'Pemeriksaan panel listrik',
      activityType: 'Inspection',
      submissionTime: '18 Juni 2026, 14:35',
      notes: 'Catatan: ditemukan kabel longgar di area panel 3.',
    },
  },
  {
    name: 'Offboarding Update',
    templateCode: 'offboarding_update',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'employee,hc',
    ccEmail: '',
    subject: '{{title}}',
    htmlContent:
      '<p>Halo {{employeeName}},</p><p>{{intro}}</p><p>Status: {{status}}</p><p>{{detailsSummary}}</p>',
    textContent: 'Halo {{employeeName}}, {{intro}} Status: {{status}}. {{detailsSummary}}',
    description: 'Update status offboarding ke karyawan dan HC.',
    variables: ['employeeName', 'title', 'intro', 'status', 'detailsSummary'],
    sampleValues: {
      employeeName: 'Maya Putri',
      title: 'Offboarding disetujui',
      intro: 'Request offboarding Anda sudah diproses dan checklist clearance berjalan.',
      status: 'approved',
      detailsSummary: 'Tanggal terakhir kerja: 30 Juni 2026 | Clearance: IT, GA, Finance',
    },
  },
  {
    name: 'HC Application Received',
    templateCode: 'application_received',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'candidate,hc',
    ccEmail: '',
    subject: 'Lamaran diterima untuk {{jobTitle}}',
    htmlContent:
      '<p>Halo {{candidateName}},</p><p>Terima kasih. Lamaran Anda untuk posisi <strong>{{jobTitle}}</strong> sudah kami terima.</p><p>Sumber: {{source}}</p><p>Waktu submit: {{submittedAt}}</p>',
    textContent:
      'Halo {{candidateName}}, terima kasih. Lamaran Anda untuk posisi {{jobTitle}} sudah kami terima. Sumber: {{source}}. Waktu submit: {{submittedAt}}.',
    description: 'Konfirmasi bahwa aplikasi kandidat sudah diterima tim HC.',
    variables: ['candidateName', 'jobTitle', 'source', 'submittedAt'],
    sampleValues: {
      candidateName: 'Dina Pertiwi',
      jobTitle: 'Operator Plant',
      source: 'Careers Page',
      submittedAt: '18 Jun 2026, 09.15',
    },
  },
  {
    name: 'HC Interview Invitation',
    templateCode: 'interview_invitation',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'candidate,hc',
    ccEmail: '',
    subject: '[HERO] Undangan Interview - {{jobTitle}}',
    htmlContent:
      '<p>Halo {{candidateName}},</p><p>Anda diundang interview untuk posisi <strong>{{jobTitle}}</strong>.</p><p>Jadwal: {{date}} {{time}}</p><p>Tipe: {{interviewType}}</p><p>Lokasi/Link: {{location}}</p><p>Pewawancara: {{interviewer}}</p><p>Durasi: {{duration}} menit</p>',
    textContent:
      'Halo {{candidateName}}, Anda diundang interview untuk posisi {{jobTitle}}. Jadwal: {{date}} {{time}}. Tipe: {{interviewType}}. Lokasi/Link: {{location}}. Pewawancara: {{interviewer}}. Durasi: {{duration}} menit.',
    description: 'Override pusat untuk undangan interview kandidat.',
    variables: ['candidateName', 'jobTitle', 'date', 'time', 'interviewType', 'location', 'interviewer', 'duration'],
    sampleValues: {
      candidateName: 'Dina Pertiwi',
      jobTitle: 'Operator Plant',
      date: '25 Juni 2026',
      time: '09:00 WITA',
      interviewType: 'Offline',
      location: 'Office Meeting Room',
      interviewer: 'HC Supervisor',
      duration: '60',
    },
  },
  {
    name: 'HC Test Assigned',
    templateCode: 'test_assigned',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'candidate,hc',
    ccEmail: '',
    subject: '[HERO] Undangan Tes Online - {{jobTitle}}',
    htmlContent:
      '<p>Halo {{candidateName}},</p><p>Anda diundang mengikuti tes untuk <strong>{{jobTitle}}</strong>.</p><p>Jadwal: {{date}} {{time}}</p><p>Akses: <a href="{{testLink}}">{{testLink}}</a></p><p>Keterangan: {{location}}</p><p>Masa aktif: {{duration}} hari</p>',
    textContent:
      'Halo {{candidateName}}, Anda diundang mengikuti tes untuk {{jobTitle}}. Jadwal: {{date}} {{time}}. Akses: {{testLink}}. Keterangan: {{location}}. Masa aktif: {{duration}} hari.',
    description: 'Override pusat untuk email assignment online test kandidat.',
    variables: ['candidateName', 'jobTitle', 'date', 'time', 'location', 'duration', 'testLink'],
    sampleValues: {
      candidateName: 'Dina Pertiwi',
      jobTitle: 'Operator Plant',
      date: '25 Juni 2026',
      time: '13:00 WITA',
      location: 'Online - dapat diakses mulai 25 Juni 2026 13:00 WITA',
      duration: '7',
      testLink: 'https://hero.example.com/test/sample-key',
    },
  },
  {
    name: 'HC Onboarding Link',
    templateCode: 'hc_onboarding_link',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'candidate,hc',
    ccEmail: '',
    subject: 'Link onboarding HERO',
    htmlContent:
      '<p>Halo {{candidateName}},</p><p>Silakan lengkapi data onboarding Anda melalui link berikut:</p><p><a href="{{onboardingLink}}">{{onboardingLink}}</a></p>',
    textContent:
      'Halo {{candidateName}}, silakan lengkapi data onboarding Anda melalui link berikut: {{onboardingLink}}.',
    description: 'Link onboarding kandidat yang bisa dioverride dari Email Settings pusat.',
    variables: ['candidateName', 'onboardingLink'],
    sampleValues: {
      candidateName: 'Dina Pertiwi',
      onboardingLink: 'https://hero.example.com/onboarding/sample-token',
    },
  },
  {
    name: 'HC Offering Letter',
    templateCode: 'offering_letter',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'candidate,hc',
    ccEmail: '',
    subject: '[HERO] Surat Penawaran Kerja - {{jobTitle}}',
    htmlContent:
      '<p>Kepada Yth. <strong>{{candidateName}}</strong>,</p><p>Bersama ini kami sampaikan penawaran kerja untuk posisi <strong>{{jobTitle}}</strong> di {{companyName}}.</p><p>Surat lengkap terlampir pada email ini.</p>',
    textContent:
      'Kepada Yth. {{candidateName}}, bersama ini kami sampaikan penawaran kerja untuk posisi {{jobTitle}} di {{companyName}}. Surat lengkap terlampir pada email ini.',
    description: 'Email surat penawaran kerja kandidat dengan lampiran PDF offering.',
    variables: ['candidateName', 'jobTitle', 'companyName'],
    sampleValues: {
      candidateName: 'Dina Pertiwi',
      jobTitle: 'Operator Plant',
      companyName: 'PT Chitra Paratama',
    },
  },
  {
    name: 'HSE JSA Created',
    templateCode: 'hse_jsa_created',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'JSA baru: {{jsaNumber}}',
    htmlContent:
      '<p>JSA baru telah dibuat.</p><p>Nomor: {{jsaNumber}}</p><p>Pekerjaan: {{jobDescription}}</p><p>Risk level: {{riskLevel}}</p><p>Tim: {{teamMembers}}</p>',
    textContent:
      'JSA baru telah dibuat. Nomor: {{jsaNumber}}. Pekerjaan: {{jobDescription}}. Risk level: {{riskLevel}}. Tim: {{teamMembers}}.',
    description: 'Notifikasi saat register JSA baru dibuat.',
    variables: ['jsaNumber', 'jobDescription', 'riskLevel', 'teamMembers'],
    sampleValues: {
      jsaNumber: 'JSA/20260618/0012',
      jobDescription: 'Overhaul pompa slurry',
      riskLevel: 'High',
      teamMembers: 'Supervisor, Mechanic, Helper',
    },
  },
  {
    name: 'HSE JSA Updated',
    templateCode: 'hse_jsa_updated',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Update JSA: {{jsaNumber}}',
    htmlContent:
      '<p>JSA telah diperbarui.</p><p>Nomor: {{jsaNumber}}</p><p>Pekerjaan: {{jobDescription}}</p><p>Risk level: {{riskLevel}}</p>',
    textContent:
      'JSA telah diperbarui. Nomor: {{jsaNumber}}. Pekerjaan: {{jobDescription}}. Risk level: {{riskLevel}}.',
    description: 'Notifikasi saat dokumen JSA diperbarui.',
    variables: ['jsaNumber', 'jobDescription', 'riskLevel'],
    sampleValues: {
      jsaNumber: 'JSA/20260618/0012',
      jobDescription: 'Overhaul pompa slurry',
      riskLevel: 'Medium',
    },
  },
  {
    name: 'HSE HIRADC Register Created',
    templateCode: 'hse_hiradc_register_created',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'HIRADC register baru: {{title}}',
    htmlContent:
      '<p>Register HIRADC baru dibuat.</p><p>Judul: {{title}}</p><p>Departemen: {{department}}</p><p>Lokasi: {{location}}</p><p>Status: {{status}}</p>',
    textContent:
      'Register HIRADC baru dibuat. Judul: {{title}}. Departemen: {{department}}. Lokasi: {{location}}. Status: {{status}}.',
    description: 'Notifikasi saat register HIRADC baru dibuat.',
    variables: ['title', 'department', 'location', 'status'],
    sampleValues: {
      title: 'HIRADC Workshop Tyre',
      department: 'Maintenance',
      location: 'Workshop',
      status: 'draft',
    },
  },
  {
    name: 'HSE HIRADC Register Updated',
    templateCode: 'hse_hiradc_register_updated',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Update HIRADC register: {{title}}',
    htmlContent:
      '<p>Register HIRADC diperbarui.</p><p>Judul: {{title}}</p><p>Departemen: {{department}}</p><p>Lokasi: {{location}}</p><p>Status: {{status}}</p>',
    textContent:
      'Register HIRADC diperbarui. Judul: {{title}}. Departemen: {{department}}. Lokasi: {{location}}. Status: {{status}}.',
    description: 'Notifikasi saat register HIRADC diperbarui.',
    variables: ['title', 'department', 'location', 'status'],
    sampleValues: {
      title: 'HIRADC Workshop Tyre',
      department: 'Maintenance',
      location: 'Workshop',
      status: 'review',
    },
  },
  {
    name: 'HSE PTW Created',
    templateCode: 'hse_ptw_created',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'PTW baru: {{permitNumber}}',
    htmlContent:
      '<p>Permit To Work baru dibuat.</p><p>Nomor: {{permitNumber}}</p><p>Pekerjaan: {{projectName}}</p><p>Tipe: {{permitType}}</p><p>Lokasi: {{location}}</p><p>Risk level: {{riskLevel}}</p>',
    textContent:
      'Permit To Work baru dibuat. Nomor: {{permitNumber}}. Pekerjaan: {{projectName}}. Tipe: {{permitType}}. Lokasi: {{location}}. Risk level: {{riskLevel}}.',
    description: 'Notifikasi saat PTW baru dibuat.',
    variables: ['permitNumber', 'projectName', 'permitType', 'location', 'riskLevel'],
    sampleValues: {
      permitNumber: 'PTW-20260618-0007',
      projectName: 'Hot work di workshop',
      permitType: 'Hot Work',
      location: 'Workshop Bay 2',
      riskLevel: 'High',
    },
  },
  {
    name: 'HSE PTW Updated',
    templateCode: 'hse_ptw_updated',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Update PTW: {{permitNumber}}',
    htmlContent:
      '<p>Permit To Work diperbarui.</p><p>Nomor: {{permitNumber}}</p><p>Pekerjaan: {{projectName}}</p><p>Status: {{status}}</p><p>Risk level: {{riskLevel}}</p>',
    textContent:
      'Permit To Work diperbarui. Nomor: {{permitNumber}}. Pekerjaan: {{projectName}}. Status: {{status}}. Risk level: {{riskLevel}}.',
    description: 'Notifikasi saat PTW diperbarui.',
    variables: ['permitNumber', 'projectName', 'status', 'riskLevel'],
    sampleValues: {
      permitNumber: 'PTW-20260618-0007',
      projectName: 'Hot work di workshop',
      status: 'Approved',
      riskLevel: 'High',
    },
  },
  {
    name: 'HSE Observation Alert',
    templateCode: 'hse_observation_alert',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Observasi HSE baru: {{title}}',
    htmlContent:
      '<p>Observasi HSE baru telah dibuat.</p><p>Site: {{siteName}}</p><p>Pelapor: {{reporterName}}</p><p>Kategori: {{category}}</p><p>Severity: {{severity}}</p><p>Lokasi: {{location}}</p><p>{{notes}}</p>',
    textContent:
      'Observasi HSE baru telah dibuat. Site: {{siteName}}. Pelapor: {{reporterName}}. Kategori: {{category}}. Severity: {{severity}}. Lokasi: {{location}}. {{notes}}',
    description: 'Notifikasi saat observasi HSE baru dibuat.',
    variables: ['siteName', 'reporterName', 'title', 'category', 'severity', 'location', 'notes'],
    sampleValues: {
      siteName: 'Site ABN',
      reporterName: 'Budi Santoso',
      title: 'Unsafe action di workshop',
      category: 'Unsafe Action',
      severity: 'High',
      location: 'Workshop Line 2',
      notes: 'Catatan: operator tidak menggunakan APD lengkap.',
    },
  },
  {
    name: 'HSE Observation Status Update',
    templateCode: 'hse_observation_status_update',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Update observasi HSE: {{title}}',
    htmlContent:
      '<p>Status observasi HSE berubah.</p><p>Judul: {{title}}</p><p>Lokasi: {{location}}</p><p>Status: {{status}}</p>',
    textContent:
      'Status observasi HSE berubah. Judul: {{title}}. Lokasi: {{location}}. Status: {{status}}.',
    description: 'Update status observasi HSE.',
    variables: ['title', 'location', 'status'],
    sampleValues: {
      title: 'Unsafe action di workshop',
      location: 'Workshop Line 2',
      status: 'closed',
    },
  },
  {
    name: 'HSE Incident Alert',
    templateCode: 'hse_incident_alert',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Incident HSE baru: {{title}}',
    htmlContent:
      '<p>Incident HSE baru telah dibuat.</p><p>Tipe: {{type}}</p><p>Impact: {{impact}}</p><p>Unit: {{unitNumber}}</p><p>Status: {{status}}</p>',
    textContent:
      'Incident HSE baru telah dibuat. Tipe: {{type}}. Impact: {{impact}}. Unit: {{unitNumber}}. Status: {{status}}.',
    description: 'Alert incident HSE baru.',
    variables: ['title', 'type', 'impact', 'unitNumber', 'status'],
    sampleValues: {
      title: 'Near miss forklift',
      type: 'Near Miss',
      impact: 'Medium',
      unitNumber: 'FLT-02',
      status: 'open',
    },
  },
  {
    name: 'HSE Incident Status Update',
    templateCode: 'hse_incident_status_update',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Update incident HSE: {{title}}',
    htmlContent:
      '<p>Status incident HSE berubah.</p><p>Judul: {{title}}</p><p>Unit: {{unitNumber}}</p><p>Status: {{status}}</p>',
    textContent:
      'Status incident HSE berubah. Judul: {{title}}. Unit: {{unitNumber}}. Status: {{status}}.',
    description: 'Update status incident HSE.',
    variables: ['title', 'unitNumber', 'status'],
    sampleValues: {
      title: 'Near miss forklift',
      unitNumber: 'FLT-02',
      status: 'closed',
    },
  },
  {
    name: 'HSE Incident Record Created',
    templateCode: 'hse_incident_record_created',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Incident report baru: {{title}}',
    htmlContent:
      '<p>Incident report HSE baru dicatat.</p><p>Kategori: {{category}}</p><p>Severity: {{severity}}</p><p>PIC: {{picName}}</p><p>Status: {{investigationStatus}}</p>',
    textContent:
      'Incident report HSE baru dicatat. Kategori: {{category}}. Severity: {{severity}}. PIC: {{picName}}. Status: {{investigationStatus}}.',
    description: 'Notifikasi incident report baru.',
    variables: ['title', 'category', 'severity', 'picName', 'investigationStatus'],
    sampleValues: {
      title: 'Slip trip fall area loading',
      category: 'Accident',
      severity: 'Major',
      picName: 'Supervisor Warehouse',
      investigationStatus: 'open',
    },
  },
  {
    name: 'HSE Incident Record Status Update',
    templateCode: 'hse_incident_record_status_update',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Update incident report: {{title}}',
    htmlContent:
      '<p>Status incident report berubah.</p><p>Judul: {{title}}</p><p>Severity: {{severity}}</p><p>Status lama: {{previousStatus}}</p><p>Status baru: {{investigationStatus}}</p><p>PIC: {{picName}}</p>',
    textContent:
      'Status incident report berubah. Judul: {{title}}. Severity: {{severity}}. Status lama: {{previousStatus}}. Status baru: {{investigationStatus}}. PIC: {{picName}}.',
    description: 'Update status incident report HSE.',
    variables: ['title', 'severity', 'previousStatus', 'investigationStatus', 'picName'],
    sampleValues: {
      title: 'Slip trip fall area loading',
      severity: 'Major',
      previousStatus: 'open',
      investigationStatus: 'closed',
      picName: 'Supervisor Warehouse',
    },
  },
  {
    name: 'HSE Safety Inspection Created',
    templateCode: 'hse_safety_inspection_created',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Safety inspection baru: {{title}}',
    htmlContent:
      '<p>Safety inspection baru dibuat.</p><p>Tanggal: {{inspectionDate}}</p><p>Lokasi: {{location}}</p><p>Kategori: {{category}}</p><p>Status: {{status}}</p><p>PIC: {{picName}}</p>',
    textContent:
      'Safety inspection baru dibuat. Tanggal: {{inspectionDate}}. Lokasi: {{location}}. Kategori: {{category}}. Status: {{status}}. PIC: {{picName}}.',
    description: 'Notifikasi inspection baru.',
    variables: ['title', 'inspectionDate', 'location', 'category', 'status', 'picName'],
    sampleValues: {
      title: 'Inspeksi APAR bulanan',
      inspectionDate: '18 Juni 2026',
      location: 'Gudang Timur',
      category: 'APAR',
      status: 'Pending',
      picName: 'HSE Officer',
    },
  },
  {
    name: 'HSE Safety Inspection Status Update',
    templateCode: 'hse_safety_inspection_status_update',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Update safety inspection: {{title}}',
    htmlContent:
      '<p>Status safety inspection berubah.</p><p>Judul: {{title}}</p><p>Lokasi: {{location}}</p><p>Status lama: {{previousStatus}}</p><p>Status baru: {{status}}</p><p>PIC: {{picName}}</p>',
    textContent:
      'Status safety inspection berubah. Judul: {{title}}. Lokasi: {{location}}. Status lama: {{previousStatus}}. Status baru: {{status}}. PIC: {{picName}}.',
    description: 'Update status inspection.',
    variables: ['title', 'location', 'previousStatus', 'status', 'picName'],
    sampleValues: {
      title: 'Inspeksi APAR bulanan',
      location: 'Gudang Timur',
      previousStatus: 'Pending',
      status: 'Completed',
      picName: 'HSE Officer',
    },
  },
  {
    name: 'HSE Safety Induction Submitted',
    templateCode: 'hse_safety_induction_submitted',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hse',
    ccEmail: '',
    subject: 'Safety induction baru: {{fullName}}',
    htmlContent:
      '<p>Form safety induction baru disubmit.</p><p>Nama: {{fullName}}</p><p>Instansi: {{companyOrigin}}</p><p>Telepon: {{phoneNumber}}</p><p>Tujuan: {{purpose}}</p>',
    textContent:
      'Form safety induction baru disubmit. Nama: {{fullName}}. Instansi: {{companyOrigin}}. Telepon: {{phoneNumber}}. Tujuan: {{purpose}}.',
    description: 'Notifikasi form induction baru.',
    variables: ['fullName', 'companyOrigin', 'phoneNumber', 'purpose'],
    sampleValues: {
      fullName: 'Rina Amelia',
      companyOrigin: 'PT Vendor Safety',
      phoneNumber: '081234567890',
      purpose: 'Meeting safety briefing',
    },
  },
  {
    name: 'HSE Inventory Reminder',
    templateCode: 'hse_inventory_reminder',
    templateType: 'Reminder',
    deliveryChannel: 'email',
    recipientScope: 'hse',
    ccEmail: '',
    subject: '[HERO HSE] Pengingat Kedaluwarsa Aset: {{itemName}}',
    htmlContent:
      '<p>Aset HSE mendekati kedaluwarsa.</p><p>Nama: {{itemName}}</p><p>Kategori: {{category}}</p><p>Lokasi: {{location}}</p><p>Tanggal beli: {{purchaseDate}}</p><p>Masa berlaku: {{validityMonths}}</p><p>Tanggal expired: {{expirationDate}}</p><p>PIC: {{picName}}</p>',
    textContent:
      'Aset HSE mendekati kedaluwarsa. Nama: {{itemName}}. Kategori: {{category}}. Lokasi: {{location}}. Tanggal beli: {{purchaseDate}}. Masa berlaku: {{validityMonths}}. Tanggal expired: {{expirationDate}}. PIC: {{picName}}.',
    description: 'Reminder aset HSE mendekati expiry.',
    variables: [
      'itemName',
      'category',
      'location',
      'purchaseDate',
      'validityMonths',
      'expirationDate',
      'picName',
    ],
    sampleValues: {
      itemName: 'APAR Dry Chemical',
      category: 'Fire Safety',
      location: 'Gudang Timur',
      purchaseDate: '2025-06-18',
      validityMonths: '12 bulan',
      expirationDate: '2026-06-18',
      picName: 'HSE Warehouse',
    },
  },
  {
    name: 'HC Employee Created',
    templateCode: 'hc_employee_created',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hc',
    ccEmail: '',
    subject: 'Data employee baru: {{employeeName}}',
    htmlContent:
      '<p>Master employee baru telah dibuat.</p><p>Nama: {{employeeName}}</p><p>Employee ID: {{employeeId}}</p><p>Email: {{employeeEmail}}</p><p>Account status: {{accountStatus}}</p>',
    textContent:
      'Master employee baru telah dibuat. Nama: {{employeeName}}. Employee ID: {{employeeId}}. Email: {{employeeEmail}}. Account status: {{accountStatus}}.',
    description: 'Notifikasi data employee baru.',
    variables: ['employeeName', 'employeeId', 'employeeEmail', 'accountStatus'],
    sampleValues: {
      employeeName: 'Ayu Wulandari',
      employeeId: 'EMP-00921',
      employeeEmail: 'ayu.wulandari@company.com',
      accountStatus: 'active',
    },
  },
  {
    name: 'HC Employee Updated',
    templateCode: 'hc_employee_updated',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hc',
    ccEmail: '',
    subject: 'Update employee: {{employeeName}}',
    htmlContent:
      '<p>Data employee telah diperbarui.</p><p>Nama: {{employeeName}}</p><p>Employee ID: {{employeeId}}</p><p>Email: {{employeeEmail}}</p><p>Account status: {{accountStatus}}</p>',
    textContent:
      'Data employee telah diperbarui. Nama: {{employeeName}}. Employee ID: {{employeeId}}. Email: {{employeeEmail}}. Account status: {{accountStatus}}.',
    description: 'Notifikasi update employee.',
    variables: ['employeeName', 'employeeId', 'employeeEmail', 'accountStatus'],
    sampleValues: {
      employeeName: 'Ayu Wulandari',
      employeeId: 'EMP-00921',
      employeeEmail: 'ayu.wulandari@company.com',
      accountStatus: 'inactive',
    },
  },
  {
    name: 'HC Disciplinary Created',
    templateCode: 'hc_disciplinary_created',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hc,employee',
    ccEmail: '',
    subject: 'Tindakan disipliner baru: {{employeeName}}',
    htmlContent:
      '<p>Tindakan disipliner baru telah dibuat.</p><p>Karyawan: {{employeeName}}</p><p>Kategori: {{categoryName}}</p><p>Severity: {{severity}}</p><p>SP Level: {{spLevel}}</p><p>Status: {{status}}</p><p>No surat: {{letterNumber}}</p>',
    textContent:
      'Tindakan disipliner baru telah dibuat. Karyawan: {{employeeName}}. Kategori: {{categoryName}}. Severity: {{severity}}. SP Level: {{spLevel}}. Status: {{status}}. No surat: {{letterNumber}}.',
    description: 'Notifikasi tindakan disipliner baru.',
    variables: ['employeeName', 'categoryName', 'severity', 'spLevel', 'status', 'letterNumber'],
    sampleValues: {
      employeeName: 'Rudi Setiawan',
      categoryName: 'Pelanggaran APD',
      severity: 'High',
      spLevel: 'SP1',
      status: 'active',
      letterNumber: 'SP/HC/2026/019',
    },
  },
  {
    name: 'HC Disciplinary Status Update',
    templateCode: 'hc_disciplinary_status_update',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hc,employee',
    ccEmail: '',
    subject: 'Update disipliner: {{employeeName}}',
    htmlContent:
      '<p>Status tindakan disipliner berubah.</p><p>Karyawan: {{employeeName}}</p><p>Kategori: {{categoryName}}</p><p>SP Level: {{spLevel}}</p><p>Status: {{status}}</p>',
    textContent:
      'Status tindakan disipliner berubah. Karyawan: {{employeeName}}. Kategori: {{categoryName}}. SP Level: {{spLevel}}. Status: {{status}}.',
    description: 'Update status tindakan disipliner.',
    variables: ['employeeName', 'categoryName', 'spLevel', 'status'],
    sampleValues: {
      employeeName: 'Rudi Setiawan',
      categoryName: 'Pelanggaran APD',
      spLevel: 'SP1',
      status: 'expired',
    },
  },
  {
    name: 'HC Performance Review Created',
    templateCode: 'hc_performance_review_created',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hc,employee,reviewer',
    ccEmail: '',
    subject: 'Performance review baru: {{employeeName}}',
    htmlContent:
      '<p>Performance review baru telah dibuat.</p><p>Employee: {{employeeName}}</p><p>Reviewer: {{reviewerName}}</p><p>Cycle: {{cycleName}}</p><p>Status: {{status}}</p>',
    textContent:
      'Performance review baru telah dibuat. Employee: {{employeeName}}. Reviewer: {{reviewerName}}. Cycle: {{cycleName}}. Status: {{status}}.',
    description: 'Notifikasi review kinerja baru.',
    variables: ['employeeName', 'reviewerName', 'cycleName', 'status'],
    sampleValues: {
      employeeName: 'Maya Sari',
      reviewerName: 'Supervisor Plant',
      cycleName: 'Annual Review 2026',
      status: 'draft',
    },
  },
  {
    name: 'HC Performance Review Submitted',
    templateCode: 'hc_performance_review_submitted',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hc,employee,reviewer',
    ccEmail: '',
    subject: 'Performance review disubmit: {{employeeName}}',
    htmlContent:
      '<p>Performance review telah disubmit.</p><p>Employee: {{employeeName}}</p><p>Reviewer: {{reviewerName}}</p><p>Cycle: {{cycleName}}</p><p>Status: {{status}}</p>',
    textContent:
      'Performance review telah disubmit. Employee: {{employeeName}}. Reviewer: {{reviewerName}}. Cycle: {{cycleName}}. Status: {{status}}.',
    description: 'Notifikasi submit review kinerja.',
    variables: ['employeeName', 'reviewerName', 'cycleName', 'status'],
    sampleValues: {
      employeeName: 'Maya Sari',
      reviewerName: 'Supervisor Plant',
      cycleName: 'Annual Review 2026',
      status: 'submitted',
    },
  },
  {
    name: 'HC Performance Review Acknowledged',
    templateCode: 'hc_performance_review_acknowledged',
    templateType: 'Notification',
    deliveryChannel: 'email,bell',
    recipientScope: 'hc,employee,reviewer',
    ccEmail: '',
    subject: 'Performance review diacknowledge: {{employeeName}}',
    htmlContent:
      '<p>Performance review telah diacknowledge.</p><p>Employee: {{employeeName}}</p><p>Reviewer: {{reviewerName}}</p><p>Cycle: {{cycleName}}</p><p>Status: {{status}}</p><p>Rating: {{overallRating}}</p>',
    textContent:
      'Performance review telah diacknowledge. Employee: {{employeeName}}. Reviewer: {{reviewerName}}. Cycle: {{cycleName}}. Status: {{status}}. Rating: {{overallRating}}.',
    description: 'Notifikasi acknowledgement review kinerja.',
    variables: ['employeeName', 'reviewerName', 'cycleName', 'status', 'overallRating'],
    sampleValues: {
      employeeName: 'Maya Sari',
      reviewerName: 'Supervisor Plant',
      cycleName: 'Annual Review 2026',
      status: 'acknowledged',
      overallRating: 'A',
    },
  },
  {
    name: 'HC Recruitment Hired Email',
    templateCode: 'hired_email',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'candidate,hc',
    ccEmail: '',
    subject: 'Selamat! Anda diterima di PT Chitra Paratama',
    htmlContent:
      '<p>Halo {{candidateName}},</p><p>Anda diterima untuk posisi <strong>{{jobTitle}}</strong>.</p><p>Tanggal mulai kerja: {{startDate}}</p><p>Silakan lengkapi onboarding melalui link berikut:</p><p><a href="{{onboardingUrl}}">{{onboardingUrl}}</a></p>',
    textContent:
      'Halo {{candidateName}}, Anda diterima untuk posisi {{jobTitle}}. Tanggal mulai kerja: {{startDate}}. Lengkapi onboarding melalui {{onboardingUrl}}.',
    description: 'Override pusat untuk email kandidat yang sudah masuk tahap hired.',
    variables: ['candidateName', 'jobTitle', 'startDate', 'onboardingUrl'],
    sampleValues: {
      candidateName: 'Dina Pertiwi',
      jobTitle: 'Operator Plant',
      startDate: '24 Juni 2026',
      onboardingUrl: 'https://hero.example.com/onboarding/sample-token',
    },
  },
  {
    name: 'HC Recruitment Start Date Email',
    templateCode: 'start_date_email',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'candidate,hc',
    ccEmail: '',
    subject: 'Informasi mulai kerja {{candidateName}}',
    htmlContent:
      '<p>Halo {{candidateName}},</p><p>Selamat datang di PT Chitra Paratama.</p><p>Posisi: {{jobTitle}}</p><p>Tanggal mulai kerja: {{startDate}}</p><p>Lengkapi administrasi onboarding: <a href="{{onboardingUrl}}">{{onboardingUrl}}</a></p>',
    textContent:
      'Halo {{candidateName}}, selamat datang di PT Chitra Paratama. Posisi: {{jobTitle}}. Tanggal mulai kerja: {{startDate}}. Lengkapi administrasi onboarding: {{onboardingUrl}}.',
    description: 'Override pusat untuk email penetapan tanggal mulai kerja kandidat.',
    variables: ['candidateName', 'jobTitle', 'startDate', 'onboardingUrl'],
    sampleValues: {
      candidateName: 'Dina Pertiwi',
      jobTitle: 'Operator Plant',
      startDate: '24 Juni 2026',
      onboardingUrl: 'https://hero.example.com/onboarding/sample-token',
    },
  },
  {
    name: 'HC Recruitment Custom Bulk Email',
    templateCode: 'custom_bulk',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'candidate,hc',
    ccEmail: '',
    subject: 'Pesan dari Tim Human Capital',
    htmlContent: '<p>Halo {{candidateName}},</p><p>{{messageBodyHtml}}</p>',
    textContent: 'Halo {{candidateName}},\n\n{{messageBody}}',
    description: 'Wrapper pusat untuk email massal kustom ke kandidat.',
    variables: ['candidateName', 'messageBody', 'messageBodyHtml'],
    sampleValues: {
      candidateName: 'Dina Pertiwi',
      messageBody: 'Jadwal seleksi Anda dipindah ke Jumat pukul 09:00.',
      messageBodyHtml: 'Jadwal seleksi Anda dipindah ke Jumat pukul 09:00.',
    },
  },
  {
    name: 'HC MCU Referral To Clinic',
    templateCode: 'mcu_pengantar',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'clinic,hc',
    ccEmail: '',
    subject: '[HERO] Surat Pengantar Medical Check Up - {{candidateName}}',
    htmlContent:
      '<p>Kepada Yth. Admin {{clinicName}},</p><p>Mohon bantuannya untuk melakukan MCU calon karyawan berikut:</p><p>Nama: {{candidateName}}</p><p>Tanggal MCU: {{date}}</p><p>Paket: {{paket}}</p><p>Biaya ditagihkan ke PT Chitra Paratama.</p>',
    textContent:
      'Kepada Yth. Admin {{clinicName}}, mohon bantuannya untuk melakukan MCU calon karyawan berikut: Nama {{candidateName}}, Tanggal MCU {{date}}, Paket {{paket}}. Biaya ditagihkan ke PT Chitra Paratama.',
    description: 'Override pusat untuk surat pengantar MCU ke klinik.',
    variables: ['candidateName', 'clinicName', 'date', 'paket'],
    sampleValues: {
      candidateName: 'Dina Pertiwi',
      clinicName: 'Klinik Sehat Sentosa',
      date: '25 Juni 2026',
      paket: 'MCU Basic',
    },
  },
  {
    name: 'HC MCU Invitation',
    templateCode: 'mcu_invitation',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'candidate,hc',
    ccEmail: '',
    subject: '[HERO] Undangan Medical Check Up - {{jobTitle}}',
    htmlContent:
      '<p>Halo {{candidateName}},</p><p>Anda diundang mengikuti MCU untuk posisi <strong>{{jobTitle}}</strong>.</p><p>Klinik: {{clinicName}}</p><p>Tanggal: {{date}}</p><p>Paket: {{paket}}</p>',
    textContent:
      'Halo {{candidateName}}, Anda diundang mengikuti MCU untuk posisi {{jobTitle}}. Klinik: {{clinicName}}. Tanggal: {{date}}. Paket: {{paket}}.',
    description: 'Override pusat untuk undangan MCU ke kandidat.',
    variables: ['candidateName', 'jobTitle', 'clinicName', 'date', 'paket'],
    sampleValues: {
      candidateName: 'Dina Pertiwi',
      jobTitle: 'Operator Plant',
      clinicName: 'Klinik Sehat Sentosa',
      date: '25 Juni 2026',
      paket: 'MCU Basic',
    },
  },
  {
    name: 'HC Contract Review Reminder',
    templateCode: 'contract_review_reminder',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'approver,hc',
    ccEmail: '',
    subject: '[Contract Review] Reminder: {{employeeName}} ({{employeeSn}}) berakhir {{contractEndDate}}',
    htmlContent:
      '<p>Yth. {{recipientName}},</p><p>Contract review untuk karyawan berikut masih perlu ditindaklanjuti.</p><p>Nama: {{employeeName}}</p><p>SN: {{employeeSn}}</p><p>Section: {{employeeSection}}</p><p>Site: {{employeeSite}}</p><p>Berakhir: {{contractEndDate}}</p><p><a href="{{reviewLink}}">Buka review</a></p>',
    textContent:
      'Yth. {{recipientName}}, contract review untuk {{employeeName}} ({{employeeSn}}) masih perlu ditindaklanjuti. Section: {{employeeSection}}. Site: {{employeeSite}}. Berakhir: {{contractEndDate}}. Review: {{reviewLink}}.',
    description: 'Pengingat H-60/H-30/H-14/H-7/H-1 untuk workflow contract review.',
    variables: ['recipientName', 'employeeName', 'employeeSn', 'employeeSection', 'employeeSite', 'contractEndDate', 'reviewLink'],
    sampleValues: {
      recipientName: 'Ary Maulana',
      employeeName: 'Budi Santoso',
      employeeSn: 'EMP-00128',
      employeeSection: 'Service',
      employeeSite: 'Balikpapan',
      contractEndDate: '31 Juli 2026',
      reviewLink: 'https://hero.example.com/dashboard/hc/contract-review/form/15',
    },
  },
  {
    name: 'HC Contract Review Approval Notification',
    templateCode: 'contract_review_approval_notification',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'approver,hc',
    ccEmail: '',
    subject: '[Contract Review] Menunggu Persetujuan Anda - {{employeeName}} ({{employeeSn}})',
    htmlContent:
      '<p>Yth. {{approverName}},</p><p>Contract Review berikut membutuhkan persetujuan Anda.</p><p>Nama: {{employeeName}}</p><p>SN: {{employeeSn}}</p><p>Section: {{employeeSection}}</p><p>Site: {{employeeSite}}</p><p>Tahap: {{approvalStep}}</p><p><a href="{{approvalLink}}">Buka approval</a></p>',
    textContent:
      'Yth. {{approverName}}, Contract Review berikut membutuhkan persetujuan Anda. Nama: {{employeeName}}. SN: {{employeeSn}}. Section: {{employeeSection}}. Site: {{employeeSite}}. Tahap: {{approvalStep}}. Approval: {{approvalLink}}.',
    description: 'Override pusat untuk email approver contract review.',
    variables: [
      'approverName',
      'employeeName',
      'employeeSn',
      'employeeSection',
      'employeeSite',
      'approvalStep',
      'approvalLink',
    ],
    sampleValues: {
      approverName: 'Romy Hidayat',
      employeeName: 'Budi Santoso',
      employeeSn: 'EMP-00128',
      employeeSection: 'Service',
      employeeSite: 'Balikpapan',
      approvalStep: 'Step 3',
      approvalLink: 'https://hero.example.com/review/sample-token',
    },
  },
  {
    name: 'HC Contract Review Test Notification',
    templateCode: 'contract_review_test_notification',
    templateType: 'Notification',
    deliveryChannel: 'email',
    recipientScope: 'approver,hc',
    ccEmail: '',
    subject: '[TEST] Contract Review - {{employeeName}}',
    htmlContent:
      '<p>Contract Review test untuk {{employeeName}} ({{employeeSn}}) telah dibuat.</p><p>Silakan buka form review: <a href="{{reviewLink}}">{{reviewLink}}</a></p>',
    textContent:
      'Contract Review test untuk {{employeeName}} ({{employeeSn}}) telah dibuat. Buka form review: {{reviewLink}}.',
    description: 'Notifikasi uji coba contract review workflow.',
    variables: ['employeeName', 'employeeSn', 'reviewLink'],
    sampleValues: {
      employeeName: 'Budi Santoso',
      employeeSn: 'EMP-00128',
      reviewLink: 'https://hero.example.com/dashboard/hc/contract-review/form/15',
    },
  },
]

export const EMAIL_TEMPLATE_PRESET_MAP = Object.fromEntries(
  EMAIL_TEMPLATE_PRESETS.map((preset) => [preset.templateCode, preset])
) satisfies Record<string, EmailTemplatePreset>
