import { db } from '../db'
import { repairFormWo } from '../db/schema/form-wo'
import { approvals } from '../db/schema/hero'
import { resolveApprovalRouteForActivity } from '../lib/approval-engine'

async function main() {
  console.log('Restoring ALL 27 historical Form WO records...')

  const dummySig =
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAAA8CAYAAAD96G4kAAAACXBIWXMAAAsTAAALEwEAmpwYAAAER0lEQVR4nO3bTWgcVRzH8e+bmd2k2SStbVqrba2K1tqK1lZt1VartmrtxVqvHjzpURDEiyAiiIgoIiKIiCIiiIgiIoqIICKKiCg'

  const allRecords = [
    // August Batch 1
    {
      noPengajuan: 'FRMWO/26/08/0001',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-08-01'),
      customer: 'PT Kaltim Prima Coal',
      site: 'CK Sangatta',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0801',
      tanggalPo: new Date('2026-08-01'),
      jobType: 'R1',
      totalAmount: 17200000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0801-001',
      tanggalWoTerbit: new Date('2026-08-02'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR230442016', noUnit: 'TRK-001', pos: 'Front', size: '27.00R49', site: 'CK Sangatta', customer: 'PT Kaltim Prima Coal', category: 'R1', price: '3500000', noWoCp: 'WO-CP-0801-001' },
        { id: '2', description: 'TR230442017', noUnit: 'TRK-002', pos: 'Rear Left', size: '27.00R49', site: 'CK Sangatta', customer: 'PT Kaltim Prima Coal', category: 'R2', price: '5200000', noWoCp: 'WO-CP-0801-001' },
        { id: '3', description: 'TR230442018', noUnit: 'TRK-003', pos: 'Rear Right', size: '29.50R25', site: 'CK Sangatta', customer: 'PT Kaltim Prima Coal', category: 'R3', price: '8500000', noWoCp: 'WO-CP-0801-001' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0002',
      jenisPengajuan: 'retread',
      tanggal: new Date('2026-08-02'),
      customer: 'PT Berau Coal',
      site: 'CK Bontang',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0802',
      tanggalPo: new Date('2026-08-02'),
      jobType: 'R2',
      totalAmount: 4750000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0802-002',
      tanggalWoTerbit: new Date('2026-08-03'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR230551001', noUnit: 'HLT-010', pos: 'Front', size: '12.00R24', site: 'CK Bontang', customer: 'PT Berau Coal', category: 'R2', price: '2800000', noWoCp: 'WO-CP-0802-002' },
        { id: '2', description: 'TR230551002', noUnit: 'HLT-011', pos: 'Rear', size: '12.00R24', site: 'CK Bontang', customer: 'PT Berau Coal', category: 'R1', price: '1950000', noWoCp: 'WO-CP-0802-002' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0003',
      jenisPengajuan: 'service',
      tanggal: new Date('2026-08-03'),
      customer: 'PT. CIPTA KRIDATAMA',
      site: 'CK Sangatta',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-CK-003',
      tanggalPo: new Date('2026-08-03'),
      jobType: 'Service',
      totalAmount: 14500000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0803-003',
      tanggalWoTerbit: new Date('2026-08-04'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'Periodic Maintenance 250H', job: 'Service', customer: 'PT. CIPTA KRIDATAMA', site: 'CK Sangatta', serialNo: 'SN-003', refNo: 'REF-003', price: '14500000', noWoCp: 'WO-CP-0803-003' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0004',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-08-04'),
      customer: 'PT Kaltim Prima Coal',
      site: 'Sangatta',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0804',
      tanggalPo: new Date('2026-08-04'),
      jobType: 'R1',
      totalAmount: 8500000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0804-004',
      tanggalWoTerbit: new Date('2026-08-05'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-004-A', noUnit: 'TRK-004', pos: 'Front', size: '27.00R49', site: 'Sangatta', customer: 'PT Kaltim Prima Coal', category: 'R1', price: '8500000', noWoCp: 'WO-CP-0804-004' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0005',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-08-05'),
      customer: 'PT Saptaindra Sejati',
      site: 'Adaro',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0805',
      tanggalPo: new Date('2026-08-05'),
      jobType: 'R2',
      totalAmount: 9200000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0805-005',
      tanggalWoTerbit: new Date('2026-08-06'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-005-B', noUnit: 'TRK-005', pos: 'Rear', size: '27.00R49', site: 'Adaro', customer: 'PT Saptaindra Sejati', category: 'R2', price: '9200000', noWoCp: 'WO-CP-0805-005' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0006',
      jenisPengajuan: 'service',
      tanggal: new Date('2026-08-06'),
      customer: 'PT TRAKINDO UTAMA',
      site: 'Balikpapan',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-TRK-006',
      tanggalPo: new Date('2026-08-06'),
      jobType: 'Service',
      totalAmount: 18000000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0806-006',
      tanggalWoTerbit: new Date('2026-08-07'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'Overhaul Tire Handling System', job: 'Service', customer: 'PT TRAKINDO UTAMA', site: 'Balikpapan', serialNo: 'SN-006', refNo: 'REF-006', price: '18000000', noWoCp: 'WO-CP-0806-006' },
      ]),
    },

    // August Batch 2
    {
      noPengajuan: 'FRMWO/26/08/0011',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-08-11'),
      customer: 'PT Madhani Talatah Nusantara',
      site: 'MTN - Berau',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0811',
      tanggalPo: new Date('2026-08-11'),
      jobType: 'R1',
      totalAmount: 6400000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0811-011',
      tanggalWoTerbit: new Date('2026-08-12'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-011', noUnit: 'MTN-01', pos: 'Front', size: '24.00R35', site: 'MTN - Berau', customer: 'PT Madhani Talatah Nusantara', category: 'R1', price: '6400000', noWoCp: 'WO-CP-0811-011' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0012',
      jenisPengajuan: 'service',
      tanggal: new Date('2026-08-12'),
      customer: 'PT. PAMAPERSADA NUSANTARA',
      site: 'Balikpapan',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-PAMA-012',
      tanggalPo: new Date('2026-08-12'),
      jobType: 'Service',
      totalAmount: 11200000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0812-012',
      tanggalWoTerbit: new Date('2026-08-13'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'Tire Fitting & Pressure Inspection', job: 'Service', customer: 'PT. PAMAPERSADA NUSANTARA', site: 'Balikpapan', serialNo: 'SN-012', refNo: 'REF-012', price: '11200000', noWoCp: 'WO-CP-0812-012' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0017',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-08-17'),
      customer: 'PT Vale Indonesia',
      site: 'Sorowako',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0817',
      tanggalPo: new Date('2026-08-17'),
      jobType: 'R2',
      totalAmount: 15400000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0817-017',
      tanggalWoTerbit: new Date('2026-08-18'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-017', noUnit: 'VALE-10', pos: 'Front Left', size: '33.00R51', site: 'Sorowako', customer: 'PT Vale Indonesia', category: 'R2', price: '15400000', noWoCp: 'WO-CP-0817-017' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0018',
      jenisPengajuan: 'retread',
      tanggal: new Date('2026-08-18'),
      customer: 'PT Petrosea Tbk',
      site: 'Petrosea SDA',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0818',
      tanggalPo: new Date('2026-08-18'),
      jobType: 'R1',
      totalAmount: 7800000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0818-018',
      tanggalWoTerbit: new Date('2026-08-19'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-018', noUnit: 'PTS-02', pos: 'Rear Right', size: '23.5R25', site: 'Petrosea SDA', customer: 'PT Petrosea Tbk', category: 'R1', price: '7800000', noWoCp: 'WO-CP-0818-018' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0019',
      jenisPengajuan: 'service',
      tanggal: new Date('2026-08-19'),
      customer: 'PT Cipta Kridatama',
      site: 'CK BIB',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-CK-019',
      tanggalPo: new Date('2026-08-19'),
      jobType: 'Service',
      totalAmount: 13600000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0819-019',
      tanggalWoTerbit: new Date('2026-08-20'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'Wheel Alignment & Rotation', job: 'Service', customer: 'PT Cipta Kridatama', site: 'CK BIB', serialNo: 'SN-019', refNo: 'REF-019', price: '13600000', noWoCp: 'WO-CP-0819-019' },
      ]),
    },

    // August Batch 3
    {
      noPengajuan: 'FRMWO/26/08/0025',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-08-25'),
      customer: 'PT Kaltim Prima Coal',
      site: 'Sangatta',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0825',
      tanggalPo: new Date('2026-08-25'),
      jobType: 'R1',
      totalAmount: 12500000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0825-025',
      tanggalWoTerbit: new Date('2026-08-26'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-025', noUnit: 'KPC-05', pos: 'Front', size: '27.00R49', site: 'Sangatta', customer: 'PT Kaltim Prima Coal', category: 'R1', price: '12500000', noWoCp: 'WO-CP-0825-025' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0026',
      jenisPengajuan: 'retread',
      tanggal: new Date('2026-08-26'),
      customer: 'PT Berau Coal',
      site: 'Tj. Redeb - Berau',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0826',
      tanggalPo: new Date('2026-08-26'),
      jobType: 'R2',
      totalAmount: 5600000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0826-026',
      tanggalWoTerbit: new Date('2026-08-27'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-026', noUnit: 'BC-22', pos: 'Rear', size: '12.00R24', site: 'Tj. Redeb - Berau', customer: 'PT Berau Coal', category: 'R2', price: '5600000', noWoCp: 'WO-CP-0826-026' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0027',
      jenisPengajuan: 'service',
      tanggal: new Date('2026-08-27'),
      customer: 'PT. CIPTA KRIDATAMA',
      site: 'CK MHU',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-CK-027',
      tanggalPo: new Date('2026-08-27'),
      jobType: 'Service',
      totalAmount: 16700000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0827-027',
      tanggalWoTerbit: new Date('2026-08-28'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'Tire Condition Monitoring System (TCMS)', job: 'Service', customer: 'PT. CIPTA KRIDATAMA', site: 'CK MHU', serialNo: 'SN-027', refNo: 'REF-027', price: '16700000', noWoCp: 'WO-CP-0827-027' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0028',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-08-28'),
      customer: 'PT Saptaindra Sejati',
      site: 'Tj. Adaro',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0828',
      tanggalPo: new Date('2026-08-28'),
      jobType: 'R1',
      totalAmount: 10400000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0828-028',
      tanggalWoTerbit: new Date('2026-08-29'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-028', noUnit: 'SIS-08', pos: 'Front', size: '27.00R49', site: 'Tj. Adaro', customer: 'PT Saptaindra Sejati', category: 'R1', price: '10400000', noWoCp: 'WO-CP-0828-028' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0029',
      jenisPengajuan: 'retread',
      tanggal: new Date('2026-08-29'),
      customer: 'PT Madhani Talatah Nusantara',
      site: 'MTN - ME',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-2026-0829',
      tanggalPo: new Date('2026-08-29'),
      jobType: 'R2',
      totalAmount: 6200000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0829-029',
      tanggalWoTerbit: new Date('2026-08-30'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-029', noUnit: 'MTN-44', pos: 'Rear', size: '24.00R35', site: 'MTN - ME', customer: 'PT Madhani Talatah Nusantara', category: 'R2', price: '6200000', noWoCp: 'WO-CP-0829-029' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0030',
      jenisPengajuan: 'service',
      tanggal: new Date('2026-08-30'),
      customer: 'PT TRAKINDO UTAMA',
      site: 'Balikpapan',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-TRK-030',
      tanggalPo: new Date('2026-08-30'),
      jobType: 'Service',
      totalAmount: 21000000,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0830-030',
      tanggalWoTerbit: new Date('2026-08-31'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'Comprehensive Hydraulic & Service Pack', job: 'Service', customer: 'PT TRAKINDO UTAMA', site: 'Balikpapan', serialNo: 'SN-030', refNo: 'REF-030', price: '21000000', noWoCp: 'WO-CP-0830-030' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/08/0031',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-08-31'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'bcv',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '5643524',
      tanggalPo: new Date('2026-08-31'),
      jobType: 'Repair',
      totalAmount: 34542324,
      statusPengajuan: 'approved',
      noWoTerbit: 'WO-CP-0831-031',
      tanggalWoTerbit: new Date('2026-08-31'),
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-34542', noUnit: 'ABN-99', pos: 'POS-2', size: '27.00R49', site: 'bcv', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: 'WO-CP-0831-031', price: '34542324' },
      ]),
    },

    // September Batch
    {
      noPengajuan: 'FRMWO/26/09/0032',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-09-01'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'bcv',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '5643524',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Repair',
      totalAmount: 34542324,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-34542', noUnit: 'ABN-99', pos: 'POS-2', size: '27.00R49', site: 'bcv', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: '', price: '34542324' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0036',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-09-01'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'bcv',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '5643524',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Repair',
      totalAmount: 34542324,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-34542', noUnit: 'ABN-99', pos: 'POS-2', size: '27.00R49', site: 'bcv', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: '', price: '34542324' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0037',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-09-01'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'bcv',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '5643524',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Repair',
      totalAmount: 34542324,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-34542', noUnit: 'ABN-99', pos: 'POS-2', size: '27.00R49', site: 'bcv', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: '', price: '34542324' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0038',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-09-01'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'bcv',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '5643524',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Repair',
      totalAmount: 34542324,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-34542', noUnit: 'ABN-99', pos: 'POS-2', size: '27.00R49', site: 'bcv', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: '', price: '34542324' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0039',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-09-01'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'bcv',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '5643524',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Repair',
      totalAmount: 34542324,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-34542', noUnit: 'ABN-99', pos: 'POS-2', size: '27.00R49', site: 'bcv', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: '', price: '34542324' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0040',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-09-01'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'fsdfhj',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '3456uy1',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Repair',
      totalAmount: 456789,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-456789', noUnit: 'ABN-01', pos: 'POS-1', size: '27.00R49', site: 'fsdfhj', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: '', price: '456789' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0041',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-09-01'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'fsdfhj',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '3456uy1',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Repair',
      totalAmount: 456789,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-456789', noUnit: 'ABN-01', pos: 'POS-1', size: '27.00R49', site: 'fsdfhj', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: '', price: '456789' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0042',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-09-01'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'fsdfhj',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '3456uy1',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Repair',
      totalAmount: 456789,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-456789', noUnit: 'ABN-01', pos: 'POS-1', size: '27.00R49', site: 'fsdfhj', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: '', price: '456789' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0043',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-09-01'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'fsdfhj',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '3456uy1',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Repair',
      totalAmount: 456789,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-456789', noUnit: 'ABN-01', pos: 'POS-1', size: '27.00R49', site: 'fsdfhj', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: '', price: '456789' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0044',
      jenisPengajuan: 'repair',
      tanggal: new Date('2026-09-01'),
      customer: 'ANDALAN BHUMI NUSANTARA',
      site: 'fsdfhj',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '3456uy1',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Repair',
      totalAmount: 456789,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'TR-456789', noUnit: 'ABN-01', pos: 'POS-1', size: '27.00R49', site: 'fsdfhj', customer: 'ANDALAN BHUMI NUSANTARA', category: 'R1', noWoCp: '', price: '456789' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0045',
      jenisPengajuan: 'service',
      tanggal: new Date('2026-09-01'),
      customer: 'PT. PAMAPERSADA NUSANTARA',
      site: 'testing',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: 'PO-PAMA-001',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Service Tire Maintenance',
      totalAmount: 15500000,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'Maintenance & Service Regular', job: 'Service', customer: 'PT. PAMAPERSADA NUSANTARA', site: 'testing', serialNo: 'SN-PAMA-091', refNo: 'REF-001', price: '15500000', noWoCp: '' },
      ]),
    },
    {
      noPengajuan: 'FRMWO/26/09/0013',
      jenisPengajuan: 'service',
      tanggal: new Date('2026-09-01'),
      customer: 'PT. CIPTA KRIDATAMA',
      site: 'TES',
      pemohon: 'Mochamad Annas Khadafi',
      pemohonJobTitle: 'Fullstack Developer',
      noPo: '1234567',
      tanggalPo: new Date('2026-09-01'),
      jobType: 'Service',
      totalAmount: 12345678,
      statusPengajuan: 'pending',
      submitterSignatureUrl: dummySig,
      items: JSON.stringify([
        { id: '1', description: 'Service Regular CK', job: 'Service', customer: 'PT. CIPTA KRIDATAMA', site: 'TES', serialNo: 'CK-001', refNo: 'REF-123', price: '12345678', noWoCp: '' },
      ]),
    },
  ]

  // Clean first
  await db.delete(approvals)
  await db.delete(repairFormWo)

  for (const rec of allRecords) {
    const [inserted] = await db
      .insert(repairFormWo)
      .values({
        ...rec,
        createdBy: '5',
        createdAt: rec.tanggal,
        updatedAt: rec.tanggal,
      })
      .returning({ id: repairFormWo.id })

    const isService = rec.jenisPengajuan === 'service'
    const custLower = (rec.customer || '').toLowerCase()
    const isMvc =
      custLower.includes('trakindo') ||
      custLower.includes('cipta kridatama') ||
      custLower.includes('ckb') ||
      custLower.trim() === 'ck'

    const transactionType = isService
      ? isMvc
        ? 'form_wo_service_mvc'
        : 'form_wo_service_other'
      : 'form_wo_repair_retread'

    const route = await resolveApprovalRouteForActivity({
      employeeId: 5,
      activityType: 'Form WO',
      priority: 'normal',
      overtimeMinutes: 0,
      transactionType,
      customerName: rec.customer,
      siteName: rec.site,
    })

    if (route.steps.length > 0) {
      for (const step of route.steps) {
        const isStep1 = step.stepOrder === 1
        const isCompleted = rec.statusPengajuan === 'approved'
        const stepStatus = isCompleted ? 'approved' : isStep1 ? 'pending' : 'waiting'

        await db.insert(approvals).values({
          repairFormWoId: inserted.id,
          level: step.stepOrder,
          approverName: step.approverName,
          approverEmployeeId: step.approverEmployeeId,
          approverNodeId: step.approverNodeId,
          approvalMatrixId: route.matrixId ?? null,
          approvalStepId: step.approvalMatrixStepId ?? null,
          status: stepStatus,
          reviewedAt: isCompleted ? rec.tanggal : null,
          signatureUrl: isCompleted ? dummySig : null,
          submittedAt: rec.tanggal,
          resolutionSource: step.resolutionSource,
          routeSnapshot: JSON.stringify({
            label: step.label,
            nodeLabel: step.nodeLabel,
            fallbackLabel: step.fallbackLabel,
            escalationLabel: step.escalationLabel,
          }),
        })
      }
    }
  }

  console.log(`✅ ALL ${allRecords.length} historical Form WO records have been restored successfully!`)
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
